name: NextJS Crypto Application

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: 
          - 20.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ${{ github.workspace }}/yarn.lock

      - run: yarn install

      - name: Build Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          run: |
          docker build \
            -t nextjs_crypto_app \
            .
          docker tag nextjs_crypto_app:latest nguyenvanhuan243/nextjs_crypto_app:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker push nguyenvanhuan243/nextjs_crypto_app:latest
      - name: Deploy Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          curl -X GET https://api.render.com/deploy/srv-coj5m78l5elc73diaaug?key=HTGmWEW1VGA